{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE Safe #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeFamilyDependencies #-}
{-# OPTIONS_GHC -Wno-unrecognised-pragmas #-}

{-# HLINT ignore "Avoid lambda" #-}
{-# HLINT ignore "Use const" #-}
{-# HLINT ignore "Redundant bracket" #-}

-- This file is generated by MtgPure.Model.ToObjectN.CodeGen
module MtgPure.Model.ToObjectN.Classes
  ( ToObject1 (..),
    ToObject2 (..),
    ToObject3 (..),
    ToObject4 (..),
    ToObject5 (..),
    ToObject6 (..),
    ToObject7 (..),
    ToObject8 (..),
  )
where

import Data.Inst
  ( Inst1,
    Inst2,
    Inst3,
    Inst4,
    Inst5,
    Inst6,
    Inst7,
    Inst8,
  )
import MtgPure.Model.IsObjectType (IsObjectType)
import MtgPure.Model.ObjectN (ObjectN (..))

class Inst1 IsObjectType a => ToObject1 o a where
  toObject1 :: o -> (ObjectN a)

class Inst2 IsObjectType a b => ToObject2 o a b where
  toObject2 :: o -> (ObjectN '(a, b))

class Inst3 IsObjectType a b c => ToObject3 o a b c where
  toObject3 :: o -> (ObjectN '(a, b, c))

class Inst4 IsObjectType a b c d => ToObject4 o a b c d where
  toObject4 :: o -> (ObjectN '(a, b, c, d))

class Inst5 IsObjectType a b c d e => ToObject5 o a b c d e where
  toObject5 :: o -> (ObjectN '(a, b, c, d, e))

class Inst6 IsObjectType a b c d e f => ToObject6 o a b c d e f where
  toObject6 :: o -> (ObjectN '(a, b, c, d, e, f))

class Inst7 IsObjectType a b c d e f g => ToObject7 o a b c d e f g where
  toObject7 :: o -> (ObjectN '(a, b, c, d, e, f, g))

class Inst8 IsObjectType a b c d e f g h => ToObject8 o a b c d e f g h where
  toObject8 :: o -> (ObjectN '(a, b, c, d, e, f, g, h))
